version: '3.4'

services:
  diagnosticscenarios:
    image: ${DOCKER_REGISTRY-}diagnosticscenarios
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
  diagsidecar:
    #image: mcr.microsoft.com/dotnet/samples:aspnetapp
    image: ${DOCKER_REGISTRY-}diagsidecar
    build:
      context: .
      dockerfile: Dockerfile_sidecar
    cap_add:
      - SYS_PTRACE
    #pid: "service:diagnosticscenarios"
